version: '3.0'

services:
  api:
    container_name: API
    build: 
      context: .
      args:
        KEY: $KEY
        MUSIX: $MUSIX
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped
